# Drawpile-LDAP-Auth-Server config
# Config options marked with "Env: NAME" may be configured in the environment as well
# Environment variables override this file

# Base64-encoded Ed25519 private key
# See README for instructions on generating this
# Env: DRAWPILE_AUTH_TOKEN_SIGNING_KEY
signingKey = ""
# The port this auth server should listen on. 8081 by default
# Env: PORT
port = 8081
# The route path the express application should look for
# Useful if you run this behind a reverse proxy on a shared domain
# Env: ROUTE
path = "/ext-auth"
# Should guests be allowed to authenticate with the server?
# Env: ALLOW_GUESTS
allowGuests = true

# General LDAP settings
# Additional options may be found at https://github.com/ldapts/ldapts#create-a-client
[ldap]
# The URL to your LDAP server
# Env: LDAP_URL
url = "ldap://localhost:389"
# The bind DN to access LDAP information without a user login
# Env: LDAP_BIND_DN
bindDN = "cn=admin,dc=example,dc=com"
# The LDAP password for the above bind user
# Env: LDAP_BIND_PASS
bindPW = "admin"
# The DN which contains your LDAP users
# Env: LDAP_USER_DN
userDN = "ou=users,dc=example,dc=com"
# The search filter to apply when searching for users
# %u is replaced with the logging-in user's username
# Env: LDAP_USER_FILTER
userSearchFilter = "(uid=%u)"
# DN which contains your LDAP groups
# Env: LDAP_GROUP_DN
groupDN = "ou=drawpile,ou=groups,dc=example,dc=com"
# The attribute used by your server to test if a user is member of a group
# You can probably leave this as the default
# Env: LDAP_MEMBER_OF_ATTR
memberOfAttribute = "memberOf"

[ldap.flagGroups]
# Defines a mapping between LDAP groups and Drawpile flags
# FLAG = "LDAP group"
MOD = "moderator"
HOST = "host"
