# Base64-encoded Ed25519 private key
signingKey = ""

[ldap]
url = "ldap://localhost:389"
bindDN = "cn=admin,dc=example,dc=com"
bindPW = "admin"
userDN = "ou=users,dc=example,dc=com"
userSearchFilter = "(uid=%u)"
# DN which contains your LDAP groups
groupDN = "ou=drawpile,ou=groups,dc=example,dc=com"
memberOfAttribute = "memberOf"

[ldap.flagGroups]
# Defines a mapping between LDAP groups and Drawpile flags
# FLAG = "LDAP group"
MOD = "moderator"
HOST = "host"
