version: "3"

services:
  drawpile-ldap-auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./config.toml:/usr/src/app/config.toml:ro
    ports:
      - 8081:8081
