version: '3'

services:
  drawpile-ldap-auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./config.toml:/usr/src/app/config.toml:ro
    ports:
      - 8081:8081
    networks:
      - default
      - ciderandsaddle
  drawpile:
    image: callaa/drawpile-srv:2.1
    volumes:
      - drawpile:/home/drawpile
      - ./drawpile-config.ini:/home/drawpile/drawpile-config.ini:ro
    command: --sessions /home/drawpile/sessions --config /home/drawpile/drawpile-config.ini --extauth http://127.0.0.1:8081
    ports:
      - 27750:27750
    networks:
      - default
      - ciderandsaddle

volumes: 
  drawpile:

networks: 
  ciderandsaddle:
    external: true
