version: '3'

services:
  drawpile-ldap-auth-server:
    image: bytewave81/drawpile-ldap-auth-server:latest
    volumes: 
      - ./config.toml:/usr/src/app/config.toml:ro
    ports:
      - 8081:8081
